name: PlatformIO CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Install library dependencies
      run: platformio lib -g install 1
    
    - name: Run PlatformIO (receiver)
      run: |
        pushd remotetemp-receiver
        platformio run
        popd
    - name: Run PlatformIO (sensor)
      run: |
        pushd remotetemp-sensor
        platformio run
        popd
